# Generated by Django 4.2.3 on 2023-07-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='nombre',
            new_name='entrega',
        ),
    ]
